### ISSUE TITLE
Lỗi edit avatar

### ISSUE THREAD

**Issue by mrthanhdat** [webvangvn/nv4_module_cbdoan#2]
Hiện không thể edit avatar :(
<tbody class="second">
            <tr>
                <td>{LANG.avt}</td>
            <td><input type="text" name="avt" id="pic_path" value="{CBDOAN.avt}">
            <input value="{LANG.select_pic}" name="selectimg" type="button"/></td>
            </tr>
        </tbody>

**Comment by webvangvn** [comment]
đã fix

https://github.com/webvangvn/nv4_module_cbdoan/commit/226e98acc1720fb9d81eca967891783138a28de4
